@startuml
start
:Spill some ideas
into text;
if (Nonsense?) then (Maybe)
    :Send to friend for review;
    if (Like?) then (Yes)
    else (No)
        :Improve text;
    endif
    :Blog to //some.portal.org//;
else (Of course)
    stop
endif
stop
@enduml
